### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by yuokada** [mijalko/zookeeper_browser#5]
HI, @mijalko 

I'm interested in this software, but this software doesn't specify a license.
Could you specify the license?

**Comment by mijalko** [comment]
open source, free for use, use it as you wish, etc...

**Comment by yuokada** [comment]
In other words, Can I treat that this code as No-License?
https://choosealicense.com/no-license/

**Comment by mijalko** [comment]
I added MIT license. Thanks for suggestion.

**Comment by yuokada** [comment]
thanks
