### ISSUE TITLE
docker version always got Cannot connect to zookeeoer. Connection time-out

### ISSUE THREAD

**Issue by bayern01kahn** [mijalko/zookeeper_browser#7]
Hi mijialko. thanks for share good tools. but I tried your docker image. but always got 
Cannot connect to zookeeper. Connection time-out.   could you take a look when you free. thanks.

<img width="507" alt="WechatIMG1421" src="https://user-images.githubusercontent.com/26653978/63991893-126a7400-cb1c-11e9-82f4-34535633bf3b.png">

**Comment by mijalko** [comment]
Hi,
your url to zookeeper is not ok. If zookeeper is in container, then url can be something like:
myzkcontainername:2181, if container name iz myzkcontainername

**Comment by bayern01kahn** [comment]
Hi,
    Thanks for reply.  But my zookeeper is running on my local env (
127.0.0.1:2181) not in docker's containner. and could been found by
dubbo-admin.

Aleksandar Mijalkovic <notifications@github.com> 于2019年8月30日周五 下午5:17写道：

**Comment by mijalko** [comment]
Containers cannot reach services on your host machine. On mac there is option to use docker.for.mac.localhost as an url. I am not sure if there is such option for docker on linux
